services:
  - type: web
    name: textor-ai
    env: python
    region: oregon
    plan: starter
    rootDir: be
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn speech_to_text_api.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: speech_to_text_api.settings
      - key: DATABASE_URL
        fromDatabase:
          name: textor-ai-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ASSEMBLYAI_API_KEY
        sync: false

databases:
  - name: textor-ai-db
    plan: starter
    region: oregon
